//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nowaste.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cities
    {
        public Cities()
        {
            this.CityDistricts = new HashSet<CityDistricts>();
            this.Requests = new HashSet<Requests>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<CityDistricts> CityDistricts { get; set; }
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
