//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nowaste.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityDistricts
    {
        public CityDistricts()
        {
            this.Requests = new HashSet<Requests>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int cityID { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
