//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nowaste.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPersons
    {
        public ClientPersons()
        {
            this.ClientPersonPhoneNumbbers = new HashSet<ClientPersonPhoneNumbbers>();
            this.Requests = new HashSet<Requests>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public System.Guid companyID { get; set; }
    
        public virtual ICollection<ClientPersonPhoneNumbbers> ClientPersonPhoneNumbbers { get; set; }
        public virtual Companies Companies { get; set; }
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
