//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nowaste.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        public Companies()
        {
            this.ClientPersons = new HashSet<ClientPersons>();
            this.Requests = new HashSet<Requests>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string invoiceInfo { get; set; }
    
        public virtual ICollection<ClientPersons> ClientPersons { get; set; }
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
